### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by ricardolimaui** [erazor83/pyRFM#1]
Hi guys, I'm trying to implement this in beaglebone and now i'am facing this error
root@beaglebone:/var/lib/cloud9/examples/lora/pyrfm/examples# python2 rf95_server.py 
Traceback (most recent call last):
  File "rf95_server.py", line 35, in <module>
    print('HW-Version: ', ll.getVersion())
  File "../lib/ll/ll_rfm9x.py", line 220, in getVersion
    return self.PL.readRegister(RFM_REG_VERSION)
  File "../lib/pl/pl_serial_seed.py", line 67, in readRegister
    return rx[0]
IndexError: list index out of range

It's just the lib is not compatible with this linux or it's really an issue? Thank you in advance

**Comment by erazor83** [comment]
Sure you're using the right tty and your hardware works?

Seems like the python script did not get any response from the port.

**Comment by ricardolimaui** [comment]
Yes I had changed the initial name (USB0) to GS0 which is present in /dev/.
And the lora grove is working because I had it already working in Arduino.
Thank for help

**Comment by erazor83** [comment]
remove the # in line 48 and 58 in /lib/pl/pl_serial_seed.py

Get startet with examples/get_version.py

This should do a simple readRegister

    def getVersion(self):
		return self.PL.readRegister(RFM_REG_VERSION)


    def readRegister(self,addr,length=1):
		self.write(82,addr,length)
		rx=self.read(length)
		if length==1:
			return rx[0]
		else:
			return rx

The self.read(length) did not get any data so somehow after writing the command to GS0, there was no response.

Maybe you've running another tool which accesses ttyGS0 ? Any getty? Isn't GS0 also used as kernel serial console?

Maybe you should try another USART.

**Comment by ricardolimaui** [comment]
Its working !! I had to change to ttyO2. Thank you
We are not able to send only to a certain address right? Only to only gateway.
I saw in your lib you have already the rssi implemented. Any example how to use it ?
Thank you!
