### ISSUE TITLE
Can't find right UART port

### ISSUE THREAD

**Issue by Joep89** [erazor83/pyRFM#3]
Hey,
I'm using the Raspberry A3+ with the "GROVE - LORA RADIO 433MHZ" module. The uart port of GPIO pins 14 and 15 (TX&RX) is on "serial0" i tested this with 2 raspberry pi's connected to eachother with tx/rx. The lora module is connected to the same pins so in my opinion it also should be port serial, but since it's not a serial port in the code but "serial_seed" i don't know which port to use or how to fix my problem. Can you please help me out? 
The error i'm getting is:
return rx[0]
IndexError: list index out of range

**Comment by erazor83** [comment]
Serial device at the RPI should be  /dev/ttyAMA0 . Make sure you don't have any kernel related debug messages printed out at this device.

**Comment by Joep89** [comment]
I found the problem, it was another uart device that was connected and should not do anything to the uart connection. The port i had to use was ttyAMA0 and then everything works thanks!
